"""
Feature engineering utilities for time series forecasting with XGBoost.

This module replicates the logic from the original notebooks:
    - Creating lagged values of the target variable.
    - Creating multi-step target columns (shift -i).
    - Shifting time features by -1 to avoid lookahead bias.
    - Dropping rows with NaNs generated by shifts.
    - Optional detrending via log-differencing.
    - Function to inverse detrend predictions.

All functions assume the input DataFrame is already sorted by date and store_id.
"""

import pandas as pd
import numpy as np
from typing import List, Tuple, Optional

def create_lag_features(df: pd.DataFrame,
                        target_col: str,
                        n_lags: int,
                        group_col: str = 'store_id') -> Tuple[pd.DataFrame, List[str]]:
    """
    Create lagged columns of the target variable.

    Args:
        df: Input DataFrame (must contain target_col and group_col).
        target_col: Name of the target column to lag.
        n_lags: Number of lagged values to create (lag_1, lag_2, ..., lag_n).
        group_col: Column name for grouping (e.g., store_id).

    Returns:
        Tuple of (df_with_lags, list_of_lag_column_names).
    """
    lag_cols = []
    for i in range(1, n_lags + 1):
        col_name = f'{target_col}_lag_{i}'
        df[col_name] = df.groupby(group_col)[target_col].shift(i)
        lag_cols.append(col_name)
    return df, lag_cols


def create_targets(df: pd.DataFrame,
                   target_col: str,
                   n_steps: int,
                   group_col: str = 'store_id') -> Tuple[pd.DataFrame, List[str]]:
    """
    Create multi-step target columns (future values) by shifting backwards.

    Args:
        df: Input DataFrame.
        target_col: Name of the target column.
        n_steps: Number of future steps to predict (t+1, t+2, ..., t+n_steps).
        group_col: Column name for grouping.

    Returns:
        Tuple of (df_with_targets, list_of_target_column_names).
    """
    target_cols = []
    for i in range(1, n_steps + 1):
        col_name = f'target_step_{i}'
        df[col_name] = df.groupby(group_col)[target_col].shift(-i)
        target_cols.append(col_name)
    return df, target_cols


def shift_time_features(df: pd.DataFrame,
                        time_features: List[str],
                        group_col: str = 'store_id') -> pd.DataFrame:
    """
    Shift time features by -1 to align them with the prediction date.
    This prevents lookahead bias (using current day's time features to predict same day).

    Args:
        df: Input DataFrame.
        time_features: List of column names that are time-based features (e.g., day_sin, holiday).
        group_col: Column name for grouping.

    Returns:
        DataFrame with time features shifted forward by one day (per group).
    """
    df[time_features] = df.groupby(group_col)[time_features].shift(-1)
    return df


def prepare_data(df: pd.DataFrame,
                 target_col: str,
                 n_lags: int,
                 n_steps: int,
                 time_features: List[str],
                 group_col: str = 'store_id',
                 detrend: bool = False,
                 detrend_period: int = 7) -> Tuple[pd.DataFrame, pd.Series | pd.DataFrame, pd.DataFrame]:
    """
    Complete feature engineering pipeline: lags, targets, time feature shift, and optional detrending.

        1. Optionally apply log differencing (detrend) if specified.
        2. Create lag features of the (possibly detrended) target.
        3. Create multi-step targets (shift -i).
        4. Shift time features by -1 to avoid lookahead.
        5. Drop rows with NaN (due to shifts).
        6. Split into X (features) and y (target(s)).
        7. Return also a metadata DataFrame with date and store_id.

    Args:
        df: Raw input DataFrame (must contain date, group_col, target_col, time_features).
        target_col: Original target column name.
        n_lags: Number of lag features to create.
        n_steps: Forecasting horizon (number of future steps).
        time_features: List of time feature column names.
        group_col: Column name for grouping (default: 'store_id').
        detrend: If True, apply log differencing to make the series stationary.
        detrend_period: Period for differencing.

    Returns:
        Tuple of:
            - X (DataFrame of features)
            - y (Series if n_steps == 1, else DataFrame of multi-step targets)
            - meta (DataFrame with columns 'date' and group_col, aligned with X/y)
    """
    # Work on a copy to avoid modifying the original
    df = df.copy()

    # Determine the effective target column (original or detrended)
    effective_target = target_col
    if detrend:
        # Apply log transform then seasonal differencing
        log_col = f'{target_col}_log'
        diff_col = f'{target_col}_diff'
        df[log_col] = np.log(df[target_col])
        df[diff_col] = df.groupby(group_col)[log_col].diff(detrend_period)
        effective_target = diff_col
        # Keep the original target for later inverse transformation

    # Create lag features
    df, lag_cols = create_lag_features(df, effective_target, n_lags, group_col)

    # Create multi-step targets
    df, target_cols = create_targets(df, effective_target, n_steps, group_col)

    # Shift time features to avoid lookahead
    df = shift_time_features(df, time_features, group_col)

    # Drop rows with NaN (introduced by shifts)
    required_cols = lag_cols + target_cols + time_features
    df = df.dropna(subset = required_cols)

    # Sort by date and store_id for consistency
    df = df.sort_values(['date', group_col])

    # Build X matrix: all columns except date, group_col, target_cols, and any auxiliary detrend columns
    exclude_cols = [group_col, 'date'] + target_cols
    if detrend:
        exclude_cols += [target_col, log_col, diff_col]

    X_cols = [c for c in df.columns if c not in exclude_cols]
    X = df[X_cols]

    # Build y: single Series if n_steps==1, else DataFrame
    if n_steps == 1:
        y = df[target_cols[0]].squeeze()  # 1D Series (n_steps x 1)
    else:
        y = df[target_cols]               # DataFrame with n_steps columns (n_steps x n_outputs)

    # Metadata: date and store_Best MAE scoreid for later aggregation/plotting
    meta = df[[group_col]].copy()
    return X, y, meta